language: ruby

branches:
  only:
    - master
    - release

os: osx
osx_image: xcode8.1
rvm: system
env:
  global:
    # default?
    - OSX=10.12"
    - HOMEBREW_DEVELOPER="1"


notifications:
  email:
    on_success: never
    on_faiure: always

before_install:
  - bash self_tap.bash

  # attempt to set the maximum number of file descriptors (see bash manpage),
  # seems pointless because this shell doesn't persist... or does it!?
  - ulimit -n 1024

script:
  - brew test-bot
  - bash make_bottles.bash
  - ls -alh

deploy:
  - provider: bintray
    user: FIXME
    #file: /home/travis/build/ponylang/ponyc/bintray_source.json
    file: bottles-to-deploy.json
    on:
      branch: release
      condition: "$FIXME == FIXME"
    key:
      secure: FIXME
