language: ruby
os: osx
osx_image: xcode8.1
rvm: system
env:
  - OSX=10.12

notifications:
  email:
    on_success: never
    on_faiure: always

before_install:
  # default stuff from homebrew
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi

  # update to latest homebrew (no, really latest)
  - HOMEBREW_REPOSITORY="$(brew --repo)"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  - git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master
  - brew update || brew update

  # link the current directory as a tap named for this
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - echo "PWD is $PWD"
  - echo "HOMEBREW_TAP_DIR is $HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - TAP_DIR_DIR="$(dirname "$HOMEBREW_TAP_DIR")"
  - if [[ ! -d "$TAP_DIR_DIR" ]]; then mkdir "$TAP_DIR_DIR"; fi
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"

  # log more verbosely
  - export HOMEBREW_DEVELOPER="1"

  # attempt to set the maximum number of file descriptors (see bash manpage),
  # seems pointless because this shell doesn't persist... or does it!?
  - ulimit -n 1024

script:
  # default call to the test-bot
  - brew test-bot
